apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: blog
type: Opaque
stringData:
  mysql-root-password: rootpassword123
  mysql-user: bloguser
  mysql-password: blogpassword
  mysql-database: blogdb
